@extends('layouts.app')
@section('content')
<!-- day-table -->
<form action="#" method="POST">
    @csrf
    <table>
        <thead>
            <tr>
            <td>あああ</td>
            <th>21</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>01:00</td>
                <td>ううう</td>
            </tr>
            <tr>
                <td>02:00</td>
                <td>ううう</td>
            </tr>
            <tr>
                <td>03:00</td>
                <td>ううう</td>
            </tr>
            <tr>
                <td>04:00</td>
                <td>ううう</td>
            </tr>
          </tbody>
    </table>
</form>
@endsection
